name: stream_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.
  - pip

  # Pacotes críticos que PRECISAM ser do conda
  - geopandas
  - gdal
  - fiona
  - shapely
  - pyproj
  - rtree
  - libspatialindex
  - proj
  - geos

  # Streamlit e dependências nativas
  - streamlit
  - pyarrow
  - tornado
  - pandas
  - numpy

  # Folium (funciona bem via conda)
  - folium

  # O resto instala via pip (tudo Python puro)
  - pip:
      - streamlit-folium
      - plotly
      - requests
      - xyzservices
